using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Linq;
using System.ServiceProcess;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using HighwaySoluations.Softomation.TMSSystemLibrary;
using HighwaySoluations.Softomation.TMSSystemLibrary.BL;
using HighwaySoluations.Softomation.TMSSystemLibrary.IL;
using HighwaySoluations.Softomation.TMSSystemLibrary.SystemConfigurations;
using HighwaySoluations.Softomation.TMSSystemLibrary.SystemLogger;
using static HighwaySoluations.Softomation.CommonLibrary.Constants;

namespace ICDProcessService
{
    public partial class ICDProcessService : ServiceBase
    {

        /// <summary>
        /// 15.1 Request Pay (Payment Process for toll collection and refund)  60
        /// 15.2 Response Pay (Get Response of all transcation)  70
        /// 15.3 Request Plaza Details (This API is called by Acquiring Bank to get latest plaza details (i.e., lane details, plaza vehicle class, toll fare rules & pass schemes) from toll plaza operator) 78
        /// 15.4 Response Plaza Details (Get Response for Plaza Request) 81
        /// 15.5 Request Tag Details (The details can be fetched by providing either TID or vehicle registration number or Tag ID.) 91
        /// 15.6 Response Tag Details (Get Response for Tag Request) 93
        /// 15.7 SyncTime Request (sync its system's time) 99
        /// 15.8 SyncTime Response (Get Response for SyncTime Request) 100
        /// 15.9 Toll Plaza Heart Beat (Toll plaza to report the availability status of each lane of the plaza) 103
        /// 15.10 Toll Plaza Heart Beat Response (Get Response for HeartBeat Request) 107
        /// 15.11 Check Transaction Status Request (check transaction status before reconciliation which are “In-process” or for which no response is received by the toll plaza operator) 110
        /// 15.12 Check Transaction Status Response (Get Response for Status Request) 113
        /// 15.13 Get Exception Request (exception list will contain the latest status of the Tag ids) 120
        /// 15.14 Get Exception Response (Get Response for Exception Request) 122
        /// 15.15 Request Query Exception List (Get incremental exception list from the acquirer bank,contain the latest status of the Tag IDs) 129
        /// 15.16 Response Query Exception List (Get Response for Query Exception Request) 132
        /// 15.17 Set Pass Scheme Request (vehicle/ tag IDs purchased pass from toll plaza) 139
        /// 15.18 Set Pass Scheme Response(Get Response for Pass Request) 145
        /// 15.19 Notification (The Notification API is initiated by Acquirer Bank to provide detailed status of “In-Process” transactions which were generated by acquirer bank in Response Pay message. Acknowledgement for Notification API will be generated by Toll Plaza) 154
        /// 15.20 List Participants (This API will be used to fetch the Participants Details by the toll plaza) 158
        /// 15.21 Participants List Response (Get Response for List Participants Request) 160
        /// </summary>


        #region Globel Variable
        volatile int onstartCheckCount = 0;
        #region Log
        private Queue logQueue = new Queue();
        private Thread loggerThread;
        private volatile Boolean stopLoggerThread = false;
        #endregion

        #region ICD Thread
        private Thread TagRequestThread;
        private volatile Boolean stopTagRequest = false;

        private Thread ViolationAuditRequestThread;
        private volatile Boolean stopViolationAuditRequest = false;

        private Thread SyncTimeRequestThread;
        private volatile Boolean stopSyncTimeRequest = false;

        private Thread HeartBeatRequestThread;
        private volatile Boolean stopHearBeatRequest = false;

        private Thread ReqPayRequestThread;
        private volatile Boolean stopReqPayRequest = false;
        #endregion

        #region ICD Config
        ICDConfig icdConfig;
        RequestDirectoryConfig requestDirectoryConfig;
        #endregion
        #endregion

        static void Main()
        {
            ServiceBase[] ServicesToRun;
            ServicesToRun = new ServiceBase[]
            {
                new ICDProcessService()
            };
            ServiceBase.Run(ServicesToRun);
        }
        public ICDProcessService()
        {
            InitializeComponent();

            string dtone = Convert.ToString(DateTime.Now.ToShortDateString());
            //dont forget to comment this line
            //OnStart(new string[] { "ICDPS" }); //<== only for debugging
        }

        protected override void OnStart(string[] args)
        {
            try
            {
                LogMessage("Starting ICDPS logger thread...");
                loggerThread = new Thread(new ThreadStart(this.LoggerThreadFunction));
                loggerThread.IsBackground = true;
                loggerThread.Start();
                LogMessage("The ICDPS logger has been started.");
            }
            catch (Exception)
            {
                //LogMessage("Error in starting PDSS logger thread function. PDSS cannot be started. " + ex.ToString());
            }

            #region Onstart multiple call check
            onstartCheckCount++;
            if (onstartCheckCount > 1)
            {
                LogMessage("Onstart called multiple time so stopping service.");
                this.Stop();
                return;
            }
            #endregion

            #region icd Config
            icdConfig = ICDConfig.Deserialize();
            if (icdConfig == null)
            {
                LogMessage("icdConfig is config is missing");
                this.Stop();
                return;
            }
            else
            {
                if (string.IsNullOrEmpty(icdConfig.ICDVersion))
                {
                    LogMessage("ICD version is missing from config");
                    this.Stop();
                    return;
                }
            }
            requestDirectoryConfig = RequestDirectoryConfig.Deserialize();

            if (icdConfig.ICDVersion == "2.5")
            {
                try
                {
                    LogMessage("Starting ReqPay thread...");
                    ReqPayRequestThread = new Thread(new ThreadStart(this.ReqPayRequestThreadFunction));
                    ReqPayRequestThread.IsBackground = true;
                    ReqPayRequestThread.Start();
                    LogMessage("The ReqPay has been started.");
                }
                catch (Exception ex)
                {
                    LogMessage("Error in starting ReqPay thread function. " + ex.ToString());
                }

                try
                {
                    LogMessage("Starting TagRequestThread thread...");
                    TagRequestThread = new Thread(new ThreadStart(this.TagRequestThreadFunction));
                    TagRequestThread.IsBackground = true;
                    TagRequestThread.Start();
                    LogMessage("The TagRequestThread has been started.");
                }
                catch (Exception ex)
                {
                    LogMessage("Error in starting TagRequest thread function. " + ex.ToString());
                }

                try
                {
                    LogMessage("Starting SyncTimeRequest thread...");
                    SyncTimeRequestThread = new Thread(new ThreadStart(this.SyncTimeRequestThreadFunction));
                    SyncTimeRequestThread.IsBackground = true;
                    SyncTimeRequestThread.Start();
                    LogMessage("The SyncTimeRequest has been started.");
                }
                catch (Exception ex)
                {
                    LogMessage("Error in starting SyncTimeRequest thread function. " + ex.ToString());
                }

                try
                {
                    LogMessage("Starting ViolationAuditRequest thread...");
                    ViolationAuditRequestThread = new Thread(new ThreadStart(this.ViolationAuditRequestThreadFunction));
                    ViolationAuditRequestThread.IsBackground = true;
                    ViolationAuditRequestThread.Start();
                    LogMessage("The ViolationAuditRequest has been started.");
                }
                catch (Exception ex)
                {
                    LogMessage("Error in starting ViolationAuditRequest thread function. " + ex.ToString());
                }

                try
                {
                    LogMessage("Starting HearBeatRequest thread...");
                    HeartBeatRequestThread = new Thread(new ThreadStart(this.HeartBeatRequestThreadFunction));
                    HeartBeatRequestThread.IsBackground = true;
                    HeartBeatRequestThread.Start();
                    LogMessage("The HearBeatRequest has been started.");
                }
                catch (Exception ex)
                {
                    LogMessage("Error in starting HearBeatRequest thread function. " + ex.ToString());
                }
            }
            #endregion
        }

        protected override void OnStop()
        {
        }

        #region ReqPay Request
        private void ReqPayRequestThreadFunction()
        {
            stopTagRequest = false;
            while (!stopTagRequest)
            {
                try
                {
                    List<ICDRequestPaymentDetailsIL> data = ICDRequestPaymentDetailsBL.GetPendingRequest();
                    foreach (ICDRequestPaymentDetailsIL item in data)
                    {
                        GenerateRequestDetails.ProcessReqPayRequest(item, icdConfig, requestDirectoryConfig.RequestPay);
                        ICDRequestPaymentDetailsBL.RequestProcess(item);
                        Thread.Sleep(50);
                    }
                }
                catch (Exception ex)
                {
                    LogMessage("ReqPayRequestThreadFunction: Error " + ex.Message.ToString());
                }
                finally
                {
                    Thread.Sleep(50);
                }
            }
        }
        #endregion

        #region Tag Request
        private void TagRequestThreadFunction()
        {
            stopTagRequest = false;
            while (!stopTagRequest)
            {
                try
                {
                    List<ICDTagDetailsIL> data = ICDTagDetailsBL.GetPendingRequest();
                    foreach (ICDTagDetailsIL item in data)
                    {
                        GenerateRequestDetails.ProcessTagDetailsRequest(item, icdConfig, requestDirectoryConfig.RequestTagDetails);
                        ICDTagDetailsBL.RequestProcess(item);
                        Thread.Sleep(50);
                    }
                }
                catch (Exception ex)
                {
                    LogMessage("TagRequestThreadFunction: Error " + ex.Message.ToString());
                }
                finally
                {
                    Thread.Sleep(50);
                }
            }
        }
        #endregion

        #region Violation Audit Request
        private void ViolationAuditRequestThreadFunction()
        {
            stopViolationAuditRequest = false;
            while (!stopViolationAuditRequest)
            {
                try
                {
                    List<ICDViolationAuditDetailsRequestIL> data = ICDViolationAuditDetailsRequestBL.GetPendingRequest();
                    foreach (ICDViolationAuditDetailsRequestIL item in data)
                    {
                        GenerateRequestDetails.ProcessViolationAuditDetailsRequest(item, icdConfig, requestDirectoryConfig.RequestVoilationAuditDetails);
                        ICDViolationAuditDetailsRequestBL.RequestProcess(item);
                        Thread.Sleep(50);
                    }
                }
                catch (Exception ex)
                {
                    LogMessage("ViolationAuditRequestThreadFunction: Error " + ex.Message.ToString());
                }
                finally
                {
                    Thread.Sleep(50);
                }
            }
        }
        #endregion

        #region Sync Time Request
        private void SyncTimeRequestThreadFunction()
        {
            stopSyncTimeRequest = false;
            while (!stopSyncTimeRequest)
            {
                try
                {
                    List<ICDSyncTimeDetailsIL> data = ICDSyncTimeDetailsBL.GetPendingRequest();
                    foreach (ICDSyncTimeDetailsIL item in data)
                    {
                        GenerateRequestDetails.ProcessSyncTimeDetailsRequest(item, icdConfig, requestDirectoryConfig.RequestSyncTime);
                        ICDSyncTimeDetailsBL.RequestProcess(item);
                        Thread.Sleep(50);
                    }
                }
                catch (Exception ex)
                {
                    LogMessage("SyncTimeRequestThreadFunction: Error " + ex.Message.ToString());
                }
                finally
                {
                    Thread.Sleep(50);
                }
            }
        }
        #endregion

        #region Heart Beat Request
        private void HeartBeatRequestThreadFunction()
        {
            stopHearBeatRequest = false;
            while (!stopHearBeatRequest)
            {
                try
                {
                    List<ICDHeartBeatDetailsIL> data = ICDHeartBeatDetailsBL.GetPendingRequest();
                    foreach (ICDHeartBeatDetailsIL item in data)
                    {
                        GenerateRequestDetails.ProcessHeartBeatDetailsRequest(item, icdConfig, requestDirectoryConfig.RequestSyncTime);
                        ICDHeartBeatDetailsBL.RequestProcess(item);
                        Thread.Sleep(50);
                    }
                }
                catch (Exception ex)
                {
                    LogMessage("HeartBeatRequestThreadFunction: Error " + ex.Message.ToString());
                }
                finally
                {
                    Thread.Sleep(50);
                }
            }
        }
        #endregion

        #region Log Methods
        private void LogMessage(String message)
        {
            logQueue.Enqueue(Environment.NewLine + "A.T. " + DateTime.Now.ToString("hh:mm:ss.FFFF tt") + ": " + message);
        }
        private void LoggerThreadFunction()
        {
            stopLoggerThread = false;

            while (!stopLoggerThread)
            {
                try
                {
                    WriteMessageFromQueue();
                }
                catch (Exception ex)
                {

                }
                finally
                {
                    Thread.Sleep(50);
                }
            }
        }
        private void WriteMessageFromQueue()
        {
            if (logQueue.Count > 0)
            {
                String message = (String)logQueue.Dequeue();

                LogMaster.Write(message, ErrorLogModule.BackOfficeService);
            }
        }
        #endregion
    }
}
